audit_header: false
title: "Guaranteed Offer"
description: John Salkowski, a top Real Estate Agent in Philadelphia, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
client:
  name: John Salkowski
  title:
  license_number:
  about_markdown: |

  market: Philadelphia
  brand: The JRS Realty Group
  brokerage:
  address: '198 Allendale Rd. Ste #301 King of Prussia, PA 19406'
  phone: 610-756-7954
  phone_type:
  phone2:
  phone2_type:
  email: john@jrsrealtygroup.com
  url: https://www.jrsrealtygroup.com

images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.jpg
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#11467a'
  theme_color: '#4d4d4f'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#11467a'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
